#:import win kivy.core.window
#: import Animation kivy.animation.Animation
#: import ew kivy.uix.effectwidget
#: import WipeTransition kivy.uix.screenmanager
#: import Clock kivy.clock.Clock


<opt_btn@ButtonBehavior+Image>:

<RectangleFlatButton>:
    #ripple_color:0, 0, 0, .2
    #background_color: 0, 0, 0, 0 
    color: root.primary_color
    background_normal:'images/effect_empty.png'
    background_down:'images/grey_shade.jpg'
    canvas.before:
        Color:
            rgba: root.primary_color
        Line:
            width: 1.5
            rectangle: (self.x, self.y, self.width, self.height)


<TransBtn>:
    #ripple_color:0, 0, 0, .2
    #background_color: 0, 0, 0, 0
    color: root.primary_color
    background_normal:'images/effect_empty.png'
    background_down:'images/contact_board.png'
    canvas.before:
        Color:
            rgba: root.primary_color
        Line:
            width: 1.5
            rectangle: (self.x, self.y, self.width, self.height)


<Home>:
    name:"home"
    tools:tools
    cont:cont
    cont1:cont1
    cont2:cont2
    cont3:cont3
    img:img
    vault:vault
    footer:footer
    
    FloatLayout:
        Image:
            source:'images/new_back.png'
            pos:self.pos
            keep_ratio: False
            allow_stretch:True

        Image:
            pos_hint:{'center_x':.5,'y':.7}
            size_hint:1,.3
            #size: 400, 400
            allow_stretch:True
            keep_ratio:False
            source:'images/top_vault.png'
        Image:
            pos_hint:{'center_x':.5,'center_y':-.02}
            size_hint:1,.25
            #size: 400, 400
            allow_stretch:True
            keep_ratio:False
            source:'images/low_vault.png'
        FloatLayout
            id:vault
            Image:
                pos_hint:{'center_x':-.3,'center_y':.403}
                size_hint:.6,.6
                #size: 400, 400
                source:'images/vault_door.png'
            Image:
                #size: 350, 350
                size_hint:.45,.5
                source:'images/opt_frame.png'
                pos_hint:{'center_x':-.279,'center_y':.4}
                id:opt_frame
            opt_btn:
                id:profiles
                source:'images/effect_empty.png' #'images/profile_pressed.png' if self.state =='down' else 'images/effect_empty.png'
                size_hint:.45,.08
                #size_hint:None, None
                pos_hint:{'center_x':-.285,'center_y':.6}
                on_press:opt_frame.source = 'images/profile_pressed.png'
                on_release:
                    opt_frame.source = 'images/opt_frame.png'
                    root.profile()
            opt_btn:
                id:notification
                source:'images/effect_empty.png' #'images/notification_pressed.png' if self.state =='down' else 'images/effect_empty.png'
                size_hint:.45,.08
                #size_hint:None, None
                pos_hint:{'center_x':-.285,'center_y':.523}
                on_press:opt_frame.source = 'images/notification_pressed.png'
                on_release:
                    opt_frame.source = 'images/opt_frame.png'
                    root.notification()
            opt_btn:
                id:settings
                source:'images/effect_empty.png' #'images/setting_pressed.png' if self.state =='down' else 'images/effect_empty.png'
                size_hint:.45,.08
                #size_hint:None, None
                pos_hint:{'center_x':-.285,'center_y':.445}
                on_press:opt_frame.source = 'images/about_pressed.png'
                on_release:
                    opt_frame.source = 'images/opt_frame.png'
                    root.about()
                    
            opt_btn:
                id:help
                source:'images/effect_empty.png' #'images/about_pressed.png' if self.state =='down' else 'images/effect_empty.png'
                size_hint:.45,.08
                #size_hint:None, None
                pos_hint:{'center_x':-.285,'center_y':.3665}
                on_press:opt_frame.source = 'images/contact_pressed.png'
                on_release:
                    opt_frame.source = 'images/opt_frame.png'
                    #root.manager.current='about'
                    
                    root.contact()
            opt_btn:
                id:about
                source:'images/effect_empty.png' #'images/contact_pressed.png' if self.state =='down' else 'images/effect_empty.png'
                size_hint:.45,.08
                #size_hint:None, None
                pos_hint:{'center_x':-.285,'center_y':.2875}
                on_press:opt_frame.source = 'images/setting_pressed.png'
                on_release:
                    opt_frame.source = 'images/opt_frame.png'
                    #app.sett()
                    root.settings()
            opt_btn:
                id:contact
                source:'images/effect_empty.png' #'images/help_pressed.png' if self.state =='down' else 'images/effect_empty.png'
                size_hint:.45,.08
                #size_hint:None, None
                pos_hint:{'center_x':-.285,'center_y':.2095}
                on_press:opt_frame.source = 'images/help_pressed.png'
                on_release:
                    opt_frame.source = 'images/opt_frame.png'
                    root.help()
                    

        BoxLayout:
            id:header
            size_hint:1,.08
            pos_hint:{'left':1,'center_y':-.04}

            FloatLayout:
                id:footer
                Image:
                    source:'images/sort_shrink_footer.png'
                    pos_hint: {'left': 1, 'y': .98}
                    keep_ratio:False
                    allow_stretch:True
                    #size_hint: 1, .3
                BoxLayout:
                    pos_hint:{'left':1,'center_y':.5}
                    #size_hint_x:20
                    spacing:0
                    FloatLayout:
                        size_hint_x:80
                        pos_hint: {'y': .98}
                        Image:
                            source:'images/catch_phrase.png'
                            #size_hint_x:None
                            #pox_hint:{'x':0}
                            #size_hint:None,1
                            pos_hint:{'left':1,'center_y':.5}
                        
                            
                            
                    Image:
                        size_hint_x:20
                        source:'images/tab_rotate.gif' #'images/sort_shrink_footer.png'
                        pos_hint: {'y': .98}
                        #size_hint:None, header.height
                        #height:header.height


                        #keep_ratio:False
                        #allow_stretch:True
                        #size_hint: 1, .3
                    
        BoxLayout:
            orientation:'vertical'
            FloatLayout:
                size_hint_y:5
                Image:
                    source:'images/sort_shrink_footer.png'
                    pos_hint:{'center_x':.5,'center_y':.5}
                    keep_ratio:False
                    allow_stretch:True

                Image:
                    source:'images/easyhacks_icon.png'
                    pos_hint:{'center_y':.5,'center_x':.2}
                    size_hint:.9,.8
                opt_btn:
                    source:'images/no_message.png' if self.state == 'down' else 'images/notification.png'
                    pos_hint:{'center_y':.5,'center_x':.6}
                    size_hint: .5,.5
                    on_release:root.notification()
                opt_btn:
                    source:'images/setting.png'
                    pos_hint:{'center_y':.5,'center_x':.9}
                    size_hint: .5,.5
                    on_release:
                        #app.sett()
                        root.settings()
                        #app.start_settings()
                        #root.settings()


            BoxLayout:
                size_hint_y:20
                BoxLayout:
                    FloatLayout:
                        Wheel:
                            id:outer
                            pos_hint:{'center_x':.5,'center_y':.37}
                            canvas.before:
                                PushMatrix
                                Rotate:
                                    angle: self.angle
                                    axis: 0, 0, 1
                                    origin: self.center
                            canvas.after:
                                PopMatrix
                            WhlSpin:
                                #opacity:.8
                                size_hint:.9,.9
                                #size: 400, 400
                                pos_hint: {'center_x': 0.5, 'center_y': 0.5}
                                source:'images/wheel_spinner.png'
                                on_press:
                                    #self.parent.change_speed()
                                    inneer.change_speed() if root.val else self.parent.change_speed()
                                    root.onpress()
                                    #Animation(x=vault.width/1.83).start(vault)
                                    
                        InnerWheel:
                            id:inneer
                            pos_hint:{'center_x':.5,'center_y':.37}
                            canvas.before:
                                PushMatrix
                                Rotate:
                                    angle: self.angle
                                    axis: 0, 0, 1
                                    origin: self.center
                            canvas.after:
                                PopMatrix
                            Image:
                                #opacity:.8
                                size_hint:.43,.43
                                #size: 400, 400
                                source:'images/smaller_wheel.png'
                                pos_hint: {'center_x': 0.5, 'center_y': 0.5}
                        VaultWheel:
                            pos_hint:{'center_x':.5,'center_y':.37}
                            canvas.before:
                                PushMatrix
                                Rotate:
                                    angle: self.angle
                                    axis: 0, 0, 1
                                    origin: self.center
                            canvas.after:
                                PopMatrix
                            Image:
                                #opacity:.8
                                size_hint:.25,.25
                                #size: 400, 400
                                source:'images/vault_wheel.png'
                                pos_hint: {'center_x': 0.5, 'center_y': 0.5}

                BoxLayout:
                    
            BoxLayout:
                size_hint_y:75
                BoxLayout:
                    size_hint_x:35
                    id:tools
                    FloatLayout:
                        #orientation:'vertical'
                        Label:
                            text:'Pick a Tool'
                            size_hint:1,.2
                            pos_hint:{'y':9.5, 'center_x':.55}
                        cust_btn:
                            id:data_refine
                            size_hint:1,.2
                            source:'images/sort_shrinker.png'
                            pos_hint:{'y':.75,'center_x':self.cust_pos +.05}
                            on_press:
                                cont.opacity =0
                            on_release:
                                #Clock.schedule_once(root.start_delay, 0)
                                #root.manager.current='sort'
                                Clock.schedule_once(root.shorkt, .1)
                                #root.manager.current='sort'
                                #root.shorkt()
                                Clock.schedule_once(lambda dt: root.visible(),1)
                                
                        cust_btn:
                            id:extract_plus
                            source:'images/extractor_plus.png'
                            size_hint:1,.2
                            pos_hint:{'y':.55, 'center_x':self.cust_pos +.05}
                            on_press:
                                cont1.opacity =0
                            on_release:
                                #Clock.schedule_once(root.start_delay, 0)
                                #root.manager.current='extractor'
                                Clock.schedule_once(root.email_x, .1)
                                #root.email_x()
                                Clock.schedule_once(lambda dt: root.visible(),1)
                                
                        cust_btn:
                            id:neogen
                            size_hint:1,.2
                            source:'images/neogenesis.png'
                            pos_hint:{'y':.35, 'center_x':self.cust_pos +.05}
                            on_press:
                                cont2.opacity =0
                            on_release:
                                #Clock.schedule_once(root.start_delay, 0)
                                #root.manager.current='neogen'
                                Clock.schedule_once(root.neogen, .1)
                                #root.neogen()
                                Clock.schedule_once(lambda dt: root.visible(),1)
                                
                        cust_btn:
                            id:img2txt
                            source:'images/img2txt.png'
                            size_hint:1,.2
                            pos_hint:{'y':.15, 'center_x':self.cust_pos +.05}
                            on_press:
                                cont3.opacity =0
                            on_release:
                                #root.manager.current='img2txt'
                                #Clock.schedule_once(root.start_delay, 0)
                                Clock.schedule_once(root.ocr, .1)
                                #root.ocr()
                                Clock.schedule_once(lambda dt: root.visible(),1)
                                

                                

                BoxLayout:
                    size_hint_x:65
                    PageLayout:
                        id:img
                        FloatLayout:
                            Image:
                                id:cont
                                size_hint:1,1
                                pos_hint:{'center_y':.85, 'center_x':.52}

                                source:'images/connectors.png'

                            Image:
                                id:cont1
                                size_hint:1,1
                                pos_hint:{'center_y':.655, 'center_x':.52}
                                source:'images/connectors_1.png'
                            Image:
                                id:cont2
                                size_hint:1,1
                                pos_hint:{'center_y':.45, 'center_x':.53}
                                source:'images/connectors_2.png'

                            Image:
                                id:cont3
                                size_hint:1,1
                                pos_hint:{'center_y':.25, 'center_x':.52}
                                source:'images/connectors_3.png'

<WhlSpin@ButtonBehavior+Image>:
#<innerwheel@ButtonBehavior+Image>:
<Salutation@Label+Image>



<CreateAccount>:
    name:'create account'
    FloatLayout:
        Image:
            source:'images/new_back.png'
            keep_ratio: False
            allow_stretch:True
        FloatLayout:
            id:log_in
            size_hint:1,.6
            pos_hint:{'center_x':.5,'y':.35}
            Image:
                source:'images/login_back.png'
                keep_ratio: False
                allow_stretch:True
                pos:log_in.pos
                size:log_in.size
            Label:
                text: 'Create Account Form'
                font_size: '20sp'
                #font_name: 'font/papyrus'
                pos_hint:{'center_x':.5, 'y': .8}
                size_hint: .4, .1/.6

            SortText:
                id: first_name
                multiline:False
                size_hint:.8, .05/.6
                pos_hint:{'center_x':.5,'y':.7}
                hint_text: 'First Name'

            SortText:
                id:last_name
                multiline:False
                size_hint:.8, .05/.6
                pos_hint:{'center_x':.5,'y':.55}
                hint_text:'Last Name'

            SortText:
                id:username
                multiline:False
                size_hint:.8, .05/.6
                pos_hint:{'center_x':.5,'y':.4}
                hint_text:'Username'

            SortText:
                id:email
                multiline:False
                size_hint:.8, .05/.6
                pos_hint:{'center_x':.5,'y':.25}
                hint_text:'Email Address'
            SortText:
                id:pass
                multiline:False
                size_hint:.8, .05/.6
                pos_hint:{'center_x':.5,'y':.1}
                hint_text:'Password'
                
        cust_btn:
            source:'images/sign_up.png'
            #text: 'Create Account'
            size_hint:.5, .1
            pos_hint:{'center_x':self.cust_pos,'y':.2}
            on_release:
                root.close()
                #root.manager.current= 'login'
    
        cust_btn:
            source:'images/scan_back.png'
            pos_hint: {'left':-.2, 'bottom': 1}
            size_hint:.25,.1
            on_release:
                #root.manager.current='home'
                root.dis()
        


<LoginScreen>
    name:'login'
    EffectWidget:
        effects:  [ew.VerticalBlurEffect(size=10.0),ew.HorizontalBlurEffect(size=10.0)]  if root.blur else [] #[root.effect_reference] if root.blur else []
        FloatLayout:
            Image:
                source:'images/new_back.png'
                keep_ratio: False
                allow_stretch:True
            cust_btn:
                source:'images/scan_back.png'
                pos_hint: {'left':-.2, 'bottom': 1}
                size_hint:.25,.1
                on_release:
                    #root.manager.current='home'
                    root.dis()
            
            FloatLayout:
                id:log_in
                size_hint:1,.6
                pos_hint:{'center_x':.5,'y':.35}
                Image:
                    source:'images/login_back.png'
                    keep_ratio: False
                    allow_stretch:True
                    pos:log_in.pos
                    size:log_in.size
                    
                Label:
                    text: 'User Login'
                    font_size: '30sp'
                    #font_name: 'font/papyrus'
                    pos_hint:{'center_x':.5, 'y': .8}
                    size_hint: .4, .1*.6
                SortText:
                    multiline:False
                    id:user
                    size_hint:.8, .05/.6
                    pos_hint:{'center_x':.5,'y':.5}
                    hint_text:'Email Address'
                SortText:
                    id:pass
                    multiline:False
                    size_hint:.8, .05/.6
                    pos_hint:{'center_x':.5,'y':.3}
                    hint_text:'Password'
                    password:True
                cust_btn:
                    source:'images/login.png'
                    #text: 'Sign In'
                    size_hint:.8, .08/.6
                    pos_hint:{'center_x':self.cust_pos,'y':.1}
                    on_release:
                        root.pop_up()
                        print('click')
                        #root.manager.current= 'home'
            Label:
                text: "Don't have an account yet?\nClick sign up to get one!!"
                #font_name: 'font/papyrus'
                pos_hint:{'center_x':.5, 'y': .2}
                size_hint: .4, .1
                halign:'center'
            cust_btn:
                source:'images/sign_up.png'
                #text: "Create Account Form"
                size_hint:.8, .08
                pos_hint:{'center_x':self.cust_pos,'y':.1}
                on_release:
                    #root.manager.current= 'create_account'
                    root.account()
            lbl_btn:
                text: "Forgot password?\nClick here"
                #font_name: 'font/papyrus'
                pos_hint:{'center_x':.5, 'y': 0.01}
                size_hint: .4, .1
                halign:'center'
                on_press:
                    root.forgot()


        
<Menu>:
    name: "menu"
    FloatLayout:
        Image:
            source:'images/new_back.png' #back_option.png'
            keep_ratio: False
            allow_stretch:True
        Image:
            #text: 'Easy Hacks'
            font_size: '50'
            source:'images/easy_hacks_splash.png' #clear_hacks.png'
            pos_hint:{'center_x':.5, 'y': .45}
            size_hint: .8,.6
        
        cust_btn:
            source: 'images/get_started.png'
            pos_hint:{'center_x':self.cust_pos,'y': .45}
            on_release:
                #root.manager.current = 'login'                           
                root.home()
                #root.login_page()
                

        cust_btn:
            pos_hint:{'center_x':self.cust_pos, 'y': .325}
            source:'images/policies.png'
            on_release:
                #root.manager.current = 'img2txt'
                #Clock.schedule_once(root.email_x, .4)
                root.policy()
        cust_btn:
            pos_hint:{'center_x':self.cust_pos, 'y': .2}
            source:'images/about.png'
            on_release:
                #root.manager.current = 'about'
                #Clock.schedule_once(root.about, .4)
                #Clock.schedule_once(root.ocr, .4)
                root.about()
        cust_btn:
            pos_hint:{'center_x':self.cust_pos, 'y': .075}
            source:'images/contact.png'
            on_release:
                #root.manager.current = 'contact'
                #Clock.schedule_once(root.contact, .4)
                #Clock.schedule_once(root.neo, .4)
                root.contact()
        Image:
            pos_hint:{'center_x':.5, 'y': -0.03}
            source:'images/catch_phrase.png'
            #pos_hint: {'y': .98}
            size_hint:.6, .15
            #size_hint:None, header.height
            #height:header.height



<EmailExtractor>:
    name:"extractor"
    emails:emails
    extract:extract
    
    FloatLayout:
        Image:
            source:'images/new_back.png'
            pos:self.pos
            keep_ratio: False
            allow_stretch:True

        BoxLayout:
            id:header
            size_hint:1,.22
            pos_hint:{'left':1,'y':.7}
            FloatLayout:
                Image:
                    source:'images/sort_shrink_footer.png'
                    pos_hint: {'left': 1, 'y': .7}
                    keep_ratio:False
                    allow_stretch:True
                    #size_hint: 1, .3
                Image:
                    source:'images/easyhacks_icon.png'
                    size_hint:.4,.2
                    pos_hint:{'center_x':.2,'y':1.1}
                Image:
                    source: 'images/extractor_plus_label.png'
                    #font_size: '50sp'
                    #font_name:'font/candara'
                    pos_hint: {'center_x':.5, 'y': .75}
                    size_hint: 1, .3
        RectangleFlatButton:
            text:'Tip'
            size_hint:.15, .05
            pos_hint:{'right': 1, 'top': 1}
            on_release:
                root.tip_info()
        GridLayout:
            cols: 2
            #spacing: 100, 100
            #padding: 50, 50, 50, 50
            size_hint:.9,.69
            id:gre
            pos_hint:{'center_x':.5,'y':.15}
            Scroll_A:
                id: scroll_a
                scroll_b: scroll_b
                do_scroll_y: False
                scroll_y: self.scroll_b.scroll_y
                pos_hint: {'top': 1}
                width:gre.width * .15
                size_hint_x:None
                SortText:
                    size_hint_y: None
                    #size_hint_x:None
                    
                    id:numb
                    text_size: self.width, None
                    #text: root.rslt if root.result_mod else ''
                    color: 1,1,1,1
                    height: max(self.minimum_height, scroll_a.height)
                    #height: self.texture_size[1]
                    #text: 'X' * 10000
                    disabled:True
                    halign:'center'
                    text: '\n'.join([str(n+1) for n in range(len(emails.text.split('\n')))]) if emails.focus else '\n'.join([str(n+1) for n in range(len(emails.text.split('\n')))])
            Scroll_B:
                id: scroll_b
                width:gre.width*.85
                do_scroll_y: True
                pos_hint: {'top': 1}
                size_hint_x:None
                SortText:
                    size_hint_y: None
                    id: emails
                    #text: display if root.result_mod else ''
                    hint_text: 'Enter input data here'
                    #input_type:None
                    keyboard_suggestion:True
                    use_bubble:True
                    allow_copy:True
                    multiline:True

                    height: max(self.minimum_height, scroll_b.height)
                    
                    text: root.rslt if root.result_mod else ''
        
        cust_btn:
            source:'images/extract_plus.png'
            allow_stretch:True
            keep_ratio:False
            id: extract
            pos_hint: {'center_x':self.cust_pos, 'y': .07}
            size_hint:.91,.06
            on_release:
                Clock.schedule_once(root.seat,0) 
                Clock.schedule_once(root.mode, 2) 
                Clock.schedule_once(root.other_tools,2.1)  #if '@' in emails.text else print()

        cust_btn:
            source:'images/homebtn.png' if root.result_mod else 'images/scan_back.png'
            allow_stretch:True
            keep_ratio:False
            pos_hint: {'center_x':self.cust_pos/2.702, 'y': 0}
            size_hint:.28,.06
            on_release:
                #root.manager.current='home'
                #print("Can't go back") if root.result_mod else root.dismiss()
                root.home()
        cust_btn:
            source:'images/other_attach.png' #bottom_back.png'
            pos_hint: {'center_x':self.cust_pos, 'y': 0}
            allow_stretch:True
            keep_ratio:False
            size_hint:.28,.06
            on_release:
                root.show_load()

        cust_btn:
            source:'images/other_cam.png' #bottom_back.png'
            pos_hint: {'center_x':self.cust_pos/.613, 'y': 0}
            size_hint:.28,.06
            allow_stretch:True
            keep_ratio:False
            on_release:
                root.camera()
        FloatLayout:
            id:search_mode
            Image:
                source:'images/search_frame.png'
                size_hint:.9,.2
                pos_hint:{'x':-.8,'center_y':.7}
                
            SortText:
                size_hint:.5,.05
                pos_hint:{'x':-.55,'center_y':.7}
                multiline:False
                halign:'center'
                valign:'middle'
                id:regex
            sld_btn:
                source:'images/search_click.png' if self.state =='down' else 'images/search.png'
                size_hint:.1,.2
                pos_hint:{'x':-.75,'center_y':.7}
                on_press:
                    Animation(x=0, d=.5).start(extract_mode)
                    Animation(x=0, d=.5).start(search_mode)
                on_release:
                    root.pattern_extract()
                    root.other_tools()
                
        FloatLayout:
            id:extract_mode
            #do_translation_y:False
            #size_hint_x:.9,.2
            Image:
                source:'images/mode_frame.png'
                size_hint:.9,.2
                pos_hint:{'x':-.8,'center_y':.3}
            sld_btn:
                source:'images/Xmode_click.png' if self.state =='down' else 'images/Xmode.png'
                size_hint:.05,.1
                pos_hint:{'x':.04,'center_y':.3}
                on_press:
                    Animation(x=extract_mode.width/1.3, d=.5).start(extract_mode)
            sld_btn:
                source:'images/email_click.png' if self.state =='down' else 'images/email.png'
                size_hint:.2,.15
                pos_hint:{'x':-.19,'center_y':.3}
                on_press:
                    Animation(x=0, d=.5).start(extract_mode)
                    Animation(x=0, d=.5).start(search_mode)
                    extract.source='images/@Extract.png'
            sld_btn:
                source:'images/link_click.png' if self.state =='down' else 'images/link.png'
                size_hint:.2,.15
                pos_hint:{'x':-.38,'center_y':.3}
                on_press:
                    Animation(x=0, d=.5).start(extract_mode)
                    Animation(x=0, d=.5).start(search_mode)
                    extract.source='images/extract_link.png'
            sld_btn:
                source:'images/phone_click.png' if self.state =='down' else 'images/phone.png'
                size_hint:.2,.15
                pos_hint:{'x':-.585,'center_y':.3}
                on_press:
                    Animation(x=0, d=.5).start(extract_mode)
                    Animation(x=0, d=.5).start(search_mode)
                    extract.source='images/extractor_phone.png'
            sld_btn:
                source:'images/regex_click.png' if self.state =='down' else 'images/regex.png'
                size_hint:.2,.15
                pos_hint:{'x':-.79,'center_y':.3}
                on_press:
                    Animation(x=0, d=.5).start(extract_mode)
                    Animation(x=extract_mode.width/1.3, d=.5).start(search_mode)
                    extract.source='images/extract_pattern.png'

<ma@FloatLayout+Scatter>
<sld_btn@ButtonBehavior+Image>:
<message>:
    Label:
        text: 'Successful Login'
        pos_hint: {'x': .3, 'top':.5}
        size_hint: .3, .2

<error>:
    Label:
        text: 'Wrong username or password'
        pos_hint: {'x': .3, 'top':.5}
        size_hint: .3, .2

<btn_scroll>:
    source:'images/motion_click.png' if self.state =='down' else 'images/motion_arrow.png' 
    canvas.before:
        PushMatrix
        Rotate:
            angle: 180
            origin:self.center
    canvas.after:
        PopMatrix 
    size_hint:.15,.15
    pos_hint:{'x':.75,'y':.4}
<re_btn>:
    source:'images/motion_click.png' if self.state =='down' else 'images/motion_arrow.png' 
    size_hint:.15,.15
    pos_hint:{'x':.75,'y':.7}

<Neogenesis>:
    name: "neogen"
    emails:emails
    display:emails
    FloatLayout:
        Image:
            source:'images/new_back.png'
            pos:self.pos
            keep_ratio: False
            allow_stretch:True

        BoxLayout:
            id:header
            size_hint:1,.22
            pos_hint:{'left':1,'y':.7}
            FloatLayout:
                Image:
                    source:'images/sort_shrink_footer.png'
                    pos_hint: {'left': 1, 'y': .7}
                    keep_ratio:False
                    allow_stretch:True
                    #size_hint: 1, .3
                Image:
                    source:'images/easyhacks_icon.png'
                    size_hint:.4,.2
                    pos_hint:{'center_x':.2,'y':1.1}

                Image:
                    source: 'images/neogen.png'
                    #font_size: '50sp'
                    #font_name:'font/candara'
                    pos_hint: {'center_x':.5, 'y': .7}
                    size_hint: 1, .4
        RectangleFlatButton:
            text:'Tip'
            size_hint:.15, .05
            pos_hint:{'right': 1, 'top': 1}
            on_release:
                root.tip_info()
        GridLayout:
            cols: 2
            #spacing: 100, 100
            #padding: 50, 50, 50, 50
            size_hint:.9,.69
            id:gre
            pos_hint:{'center_x':.5,'y':.15}
            Scroll_A:
                id: scroll_a
                scroll_b: scroll_b
                do_scroll_y: False
                scroll_y: self.scroll_b.scroll_y
                pos_hint: {'top': 1}
                width:gre.width * .15
                size_hint_x:None
                SortText:
                    size_hint_y: None
                    #size_hint_x:None
                    
                    id:numb
                    text_size: self.width, None
                    #text: root.rslt if root.result_mod else ''
                    color: 1,1,1,1
                    height: max(self.minimum_height, scroll_a.height)
                    #height: self.texture_size[1]
                    #text: 'X' * 10000
                    disabled:True
                    halign:'center'
                    text: '\n'.join([str(n+1) for n in range(len(emails.text.split('\n')))]) if emails.focus else '\n'.join([str(n+1) for n in range(len(emails.text.split('\n')))])
            Scroll_B:
                id: scroll_b
                width:gre.width*.85
                do_scroll_y: True
                pos_hint: {'top': 1}
                size_hint_x:None
                SortText:
                    size_hint_y: None
                    id: emails
                    #text: display if root.result_mod else ''
                    hint_text: 'Enter input data here'
                    #input_type:None
                    keyboard_suggestion:True
                    use_bubble:True
                    allow_copy:True
                    multiline:True

                    height: max(self.minimum_height, scroll_b.height)
                    
                    text: root.rslt if root.result_mod else ''
        cust_btn:
            id: generate
            source:'images/generate.png'
            #pos_hint: {'center_x':self.cust_pos, 'bottom': 1}
            #size_hint:.7,.1
            allow_stretch:True
            keep_ratio:False
            pos_hint: {'center_x':.5, 'y': .07}
            size_hint:.91,.06
            on_release:
                Clock.schedule_once(root.seat,0) if emails.text else emails.focus==True
                #Clock.schedule_once(root.mode, 2) if emails.text else emails.focus==True
                Clock.schedule_once(root.generate_emails,2) if emails.text else emails.focus==True
                Clock.schedule_once(root.check_result,2.1)  if '@' in emails.text else print()

                
                #root.other_tools() if '@' in emails.text else root.error_() 
                #root.check_msg()


        cust_btn:
            source:'images/homebtn.png' if root.result_mod else 'images/scan_back.png'
            pos_hint: {'center_x':self.cust_pos/2.702, 'y': 0}
            size_hint:.28,.06
            allow_stretch:True
            keep_ratio:False
            on_release:
                #root.manager.current='home'
                #root.dismiss() #print("Can't go back") if root.result_mod else root.dismiss()
                root.home()
        cust_btn:
            source:'images/other_attach.png' #bottom_back.png'
            pos_hint: {'center_x':self.cust_pos, 'y': 0}
            size_hint:.28,.06
            allow_stretch:True
            keep_ratio:False
            on_release:
                root.show_load()

        cust_btn:
            source:'images/other_cam.png' #bottom_back.png'
            pos_hint: {'center_x':self.cust_pos/.613, 'y': 0}
            size_hint:.28,.06
            allow_stretch:True
            keep_ratio:False
            on_release:
                Clock.schedule_once(root.seat,0)
                root.camera()




<cam_btn@ButtonBehavior+Image>:

<About>:
    FloatLayout:
        Image:
            source:'images/new_back.png'
            pos:self.pos
            keep_ratio: False
            allow_stretch:True
        CarlView:
            id:carousel
            RstDocument:
                id:first
                size_hint:.9,.75
                pos_hint: {'center_x':.5, 'center_y': .47}
                text:root.txt
            RstDocument:
                id:second
                size_hint:.9,.75
                pos_hint: {'center_x':.5, 'center_y': .47}
                text:root.txt2
            FloatLayout:
                id:third
                size_hint:.9,.75
                pos_hint: {'center_x':.5, 'center_y': .47}
                canvas:
                    Color:
                        rgba:1,1,1,1
                    Rectangle:
                        size:self.size
                        pos:self.pos
                RstDocument:
                    text:root.quicklessons
                    size_hint:1,.4
                    pos_hint: {'center_x':.5, 'top':1}
                TransBtn:
                    id:h
                    text:'Home Page'
                    size_hint:.8,.08
                    pos_hint: {'center_x':.5, 'center_y': .55}
                    on_release:
                        root.home_tutor()
                TransBtn:
                    id:d
                    text:'Data Refinery Page'
                    size_hint:.8,.08
                    pos_hint: {'center_x':.5, 'center_y': .45}
                    on_release:
                        root.data_tutor()
                TransBtn:
                    id:e
                    text:'Extractor Plus Page'
                    size_hint:.8,.08
                    pos_hint: {'center_x':.5, 'center_y': .35}
                    on_release:
                        root.extract_tutor()
                TransBtn:
                    id:n
                    text:'Nomineogen Page'
                    size_hint:.8,.08
                    pos_hint: {'center_x':.5, 'center_y': .25}
                    on_release:
                        root.neogen_tutor()
                
                TransBtn:
                    id:i
                    text:'Image Reader'
                    size_hint:.8,.08
                    pos_hint: {'center_x':.5, 'center_y': .15}
                    on_release:
                        root.ocr_tutor()
                TransBtn:
                    text:'More Tutorials'
                    size_hint:.8,.08
                    pos_hint: {'center_x':.5, 'center_y': .05}
                    on_release:
                        root.insta()

        opt_btn:
            source:'images/scan_back.png'
            pos_hint: {'left':-.2, 'bottom': 1}
            size_hint:.25,.1
            on_release:
                #root.manager.current='home'
                root.close()
        BoxLayout:
            id:header
            size_hint:1,.22
            pos_hint:{'left':1,'y':.7}
            FloatLayout:
                Image:
                    source:'images/sort_shrink_footer.png'
                    pos_hint: {'left': 1, 'y': .7}
                    keep_ratio:False
                    allow_stretch:True
                    #size_hint: 1, .3
                Image:
                    source:'images/learn.png'
                    size_hint:.7,.2
                    pos_hint:{'center_x':.5,'y':1.1}
                opt_btn:
                    id:sor_cam
                    source:'images/prologue.png'
                    cust_x:.15
                    allow_stretch:True
                    keep_ratio:False
                    pos_hint: {'center_x': self.cust_x, 'y': .8}
                    size_hint: .3, .15
                    on_press:
                        Animation(cust_x=.15, d= .5).start(sort_bar)
                        carousel.load_slide(first)
                    
                opt_btn:
                    id:sort_page
                    cust_x:.5
                    source:'images/easy_hacks_intro.png'
                    pos_hint: {'center_x': self.cust_x, 'y': .8}
                    size_hint: .3, .15
                    allow_stretch:True
                    keep_ratio:False
                    on_press:
                        #carousel.load_previous()
                        Animation(cust_x=.5, d=.5).start(sort_bar)
                        carousel.load_slide(second)
                opt_btn:
                    id:shrink_page
                    source:'images/Tutorials.png'
                    cust_x:1
                    allow_stretch:True
                    keep_ratio:False
                    pos_hint: {'right': self.cust_x, 'y': .8}
                    size_hint: .3, .15
                    on_press:
                        #carousel.load_next(mode= 'next')
                        Animation(cust_x=.85, d= .5).start(sort_bar)
                        print('pressed')
                        carousel.load_slide(third)
                Image:
                    id:sort_bar
                    cust_x:.15
                    source:'images/sort_bar.png'
                    allow_stretch:True
                    keep_ratio:False
                    pos_hint: {'center_x': self.cust_x, 'y': .7}
                    size_hint: .333, .02



<back_btn@ButtonBehavior+Image>

<Contact>:
    FloatLayout:
        Image:
            source:'images/grey_shade.jpg' #new_back.png'
            pos:self.pos
            keep_ratio: False
            allow_stretch:True
        Label:
            size_hint:.6,.1
            pos_hint: {'center_x':.5, 'y': .8}
            text:"We'd love to hear from you"
            font_size:'20sp'
            color:0,0,0,1
        SortText:
            id:subject
            multiline:False
            hint_text:'Subject'
            size_hint: .8, .05
            pos_hint: {'center_x': .5, 'y': .75}
        SortText:
            id:message
            hint_text:'\n'.join(("Tell us what feature you'd like us to add","Report a bug, Send your feedback or Make Enquiry"))
            pos_hint: {'center_x': .5, 'y': .32}
            size_hint: .8, .4

        TransBtn:
            id:msg
            text:'Send Message'
            size_hint:.5,.05
            pos_hint: {'center_x':.5, 'y': .24}
            on_press:
                root.send_message()
        opt_btn:
            id:phone
            text:'Phone:+2347066282414'
            source:'images/call.png'
            size_hint:.12,.12
            pos_hint: {'center_x':.5, 'y': .08}
            
            on_press:
                root.phone()
        opt_btn:
            id:phone
            text:'Phone:+2347066282414'
            source:'images/insta.png'
            size_hint:.12,.12
            pos_hint: {'center_x':.25, 'y': .08}
            
            on_press:
                root.insta()

        opt_btn:
            id:phone
            text:'Phone:+2347066282414'
            source:'images/whatsapp.png'
            size_hint:.12,.12
            pos_hint: {'center_x':.75, 'y': .08}
            
            on_press:
                root.whatsapp()
                
        
        BoxLayout:
            id:header
            size_hint:1,.3
            pos_hint:{'left':1,'y':.7}
            FloatLayout:
                Image:
                    source:'images/sort_shrink_footer.png'
                    pos_hint: {'left': 1, 'y': .7}
                    keep_ratio:False
                    allow_stretch:True
                    #size_hint: 1, .3
                Image:
                    size_hint:.8,.2
                    pos_hint: {'center_x':.5, 'top': .92}
                    source:"images/contact us.png"
                    font_size:'50sp'
        opt_btn:
            source:'images/homebtn.png' if root.result_mod else 'images/scan_back.png'
            pos_hint: {'left':-.2, 'bottom': 1}
            size_hint:.25,.1
            on_release:
                #root.manager.current='home'
                #root.close()
                root.home()

<ResultHead>:
    size_hint:1,.3
    pos_hint:{'left':1,'y':.7}
    FloatLayout:
        Image:
            source:'images/sort_shrink_footer.png'
            pos_hint: {'left': 1, 'y': .7}
            keep_ratio:False
            allow_stretch:True
            #size_hint: 1, .3
        Image:
            size_hint:.8,.2
            pos_hint: {'center_x':.5, 'top': .92}
            source:"images/result1.png"
            font_size:'50sp'

<treed>:
    GridLayout:
        cols: 1
        #spacing: 100, 100
        #padding: 50, 50, 50, 50
        size_hint:.9,.75
        id:gre
        pos_hint:{'center_x':.5,'top': 1}
        Scroll_C:
            id: scroll_a
            #scroll_b: scroll_b
            do_scroll_y: True
            #scroll_y: self.scroll_b.scroll_y
            pos_hint: {'top': 1}
            #width:gre.width * .15
            #size_hint_x:None
            TreeView:
                size_hint_y: None
                #size_hint_x:None
                
                id:tv
                #text_size: self.width, None
                #text: root.rslt if root.result_mod else ''
                #color: 1,1,1,1
                height: max(self.minimum_height, scroll_a.height)
                #height: self.texture_size[1]
                #text: 'X' * 10000
                #disabled:True
                #halign:'center'
                #text: '\n'.join([str(n+1) for n in range(len(emails.text.split('\n')))]) if emails.focus else '\n'.join([str(n+1) for n in range(len(emails.text.split('\n')))])
            

<ResultBody>:
    FloatLayout:
        GridLayout:
            cols: 2
            #spacing: 100, 100
            #padding: 50, 50, 50, 50
            size_hint:.9,.69
            id:gre
            pos_hint:{'center_x':.5,'center_y': .525}
            Scroll_A:
                id: scroll_a
                scroll_b: scroll_b
                do_scroll_y: False
                scroll_y: self.scroll_b.scroll_y
                pos_hint: {'top': 1}
                width:gre.width * .15
                size_hint_x:None
                SortText:
                    size_hint_y: None
                    #size_hint_x:None
                    
                    id:numb
                    text_size: self.width, None
                    #text: root.rslt if root.result_mod else ''
                    color: 1,1,1,1
                    height: max(self.minimum_height, scroll_a.height)
                    #height: self.texture_size[1]
                    #text: 'X' * 10000
                    disabled:True
                    halign:'center'
                    text: '\n'.join([str(n+1) for n in range(len(emails.text.split('\n')))]) if emails.focus else '\n'.join([str(n+1) for n in range(len(emails.text.split('\n')))])
            Scroll_B:
                id: scroll_b
                width:gre.width*.85
                do_scroll_y: True
                pos_hint: {'top': 1}
                size_hint_x:None
                SortText:
                    size_hint_y: None
                    id: emails
                    #text: display if root.result_mod else ''
                    hint_text: 'Enter input data here'
                    #input_type:None
                    keyboard_suggestion:True
                    use_bubble:True
                    allow_copy:True
                    multiline:True

                    height: max(self.minimum_height, scroll_b.height)
                    
                    text: root.result_info
<OCR>:
    name:"img2txt"
    #img:img
    #display: result
    FloatLayout:
        id:float
        Image:
            source:'images/new_back.png'
            pos:self.pos
            keep_ratio: False
            allow_stretch:True
        BoxLayout:
            id:header
            size_hint:1,.22
            pos_hint:{'left':1,'y':.7}
            FloatLayout:
                Image:
                    source:'images/sort_shrink_footer.png'
                    pos_hint: {'left': 1, 'y': .7}
                    keep_ratio:False
                    allow_stretch:True
                    #size_hint: 1, .3
                Image:
                    source:'images/easyhacks_icon.png'
                    size_hint:.4,.2
                    pos_hint:{'center_x':.2,'y':1.1}

                Image:
                    source: 'images/image_reader.png'
                    #font_size: '50sp'
                    #font_name:'font/candara'
                    pos_hint: {'center_x':.5, 'y': .7}
                    size_hint: 1, .4
        Image:
            source: 'images/ocr_cam.png' if btn_cam.state=='down' else 'images/ocr_cam_click.png'
            size_hint:.65,.65
            pos_hint:{'center_y':.51,'center_x':.68}
        opt_btn:
            id:btn_cam
            source: 'images/btn_cam.png'
            size_hint:.7/2.5,.7/2.5
            pos_hint:{'center_y':.55,'center_x':.68}
            on_release:
                Clock.schedule_once(root.seat,0)
                Clock.schedule_once(root.cam, 2) #root.take_shot()
                #root.pop_up()
        Image:
            source:'images/gallery.png' if gall.state=='down' else 'images/gallery_click.png'
            size_hint:.55,.55
            pos_hint:{'center_y':.51,'center_x':.3}
        opt_btn:
            id: gall
            source:'images/btn_gall.png'
            size_hint:.6/2.5,.6/2.5
            pos_hint:{'center_y':.55,'center_x':.29}
            on_release:root.gallery()
        Image:
            source:'images/file_choose.png' if att.state=='down' else 'images/file_choose_click.png'
            size_hint:.5,.5
            pos_hint:{'center_y':.69,'center_x':.5}
        opt_btn:
            id:att
            source:'images/btn_attach.png'
            size_hint:.55/2.5,.55/2.5
            pos_hint:{'center_y':.7,'center_x':.5}
            on_release:
                #root.show_load()
                #root.filechooser()
                root.file_picker()

        cust_btn:
            id: scan
            source:'images/scan.png'
            pos_hint: {'right':self.cust_pos/.5, 'y': 0}
            size_hint:.7,.07
            allow_stretch:True
            keep_ratio:False
            
            on_release:
                Clock.schedule_once(root.seat,0)
                #Clock.schedule_once(root.anypro, 2) #if emails.text else emails.focus==True
                Clock.schedule_once(root.expiry_date,2.1)  #if '@' in emails.text else print()

                #Clock.schedule_once(root.generate_emails,2) if emails.text else emails.focus==True
                #root.other_tools() if '@' in emails.text else root.error_() 

                #() #root.shrink()
                #Clock.schedule_once(root.other_tools, 2,1)  if root.fn else print('no')

        cust_btn:
            source:'images/homebtn.png' if root.result_mod else 'images/scan_back.png'
            pos_hint: {'left':self.cust_pos/.5, 'y': 0}
            allow_stretch:True
            keep_ratio:False
            size_hint:.28,.07
            on_release:
                #root.manager.current='home'
                #root.close()
                #print("Can't go back") if root.result_mod else root.close()
                root.home()
        Carousel:
            id:car_info
            size_hint:1,.28
            pos_hint:{'center_y':.27,'center_x':.5}
            
            Image:
                source:'images/ocr_info.png'
                size_hint:.7,1
                pos_hint:{'center_y':.45,'center_x':.5}
            
<down@Image+ButtonBehavior>:


<Sort>:
    sort_input:sort_input
    #display: result
    strin:strin
    
    FloatLayout:
        Image:
            source:'images/new_back.png'
            pos:self.pos
            keep_ratio: False
            allow_stretch:True


        CarlView:
            id:carousel
            FloatLayout:
                GridLayout:
                    cols: 2
                    #spacing: 100, 100
                    #padding: 50, 50, 50, 50
                    size_hint:.9,.69
                    id:gre
                    pos_hint:{'center_x':.5,'y':.15}
                    Scroll_A:
                        id: scroll_a
                        scroll_b: scroll_b
                        do_scroll_y: False
                        scroll_y: self.scroll_b.scroll_y
                        pos_hint: {'top': 1}
                        width:gre.width * .15
                        size_hint_x:None
                        SortText:
                            size_hint_y: None
                            #size_hint_x:None
                            
                            id:numb
                            text_size: self.width, None
                            #text: root.rslt if root.result_mod else ''
                            color: 1,1,1,1
                            height: max(self.minimum_height, scroll_a.height)
                            #height: self.texture_size[1]
                            #text: 'X' * 10000
                            disabled:True
                            halign:'center'
                            text:'\n'.join([str(n+1) for n in range(len(sort_input.text.split('\n')))]) if sort_input.focus else '\n'.join([str(n+1) for n in range(len(sort_input.text.split('\n')))])
                    Scroll_B:
                        id: scroll_b
                        width:gre.width*.85
                        do_scroll_y: True
                        pos_hint: {'top': 1}
                        size_hint_x:None
                        SortText:
                            size_hint_y: None
                            id: sort_input
                            hint_text: 'Result appears here as output'
                            input_type:'text'
                            keyboard_suggestion:True
                            use_bubble:True
                            allow_copy:True
                            color: 1,1,1,1
                            
                            height: max(self.minimum_height, scroll_b.height)
                            
                            text: root.rslt if root.result_mod else ''
                
                cust_btn:
                    id: Sort
                    source:'images/sort.png'
                    pos_hint: {'center_x':self.cust_pos, 'y': .07}
                    allow_stretch:True
                    keep_ratio:False
                    size_hint:.91,.06
                    on_release:
                        Clock.schedule_once(root.seat,0) #if sort_input.text else sort_input.focus==True
                        #Clock.schedule_once(root.mode, 2) if emails.text else emails.focus==True
                        #Clock.schedule_once(root.other_tools,2.1)  if '@' in emails.text else print()

                        #Clock.schedule_once(root.generate_emails,2) if emails.text else emails.focus==True
                        #root.other_tools() if '@' in emails.text else root.error_() 

                        Clock.schedule_once(root.sort_data, 2)
                        Clock.schedule_once(root.other_tools, 2.1)  if sort_input.text else print('none')
                        #root.clear()
                    
            FloatLayout:
                GridLayout:
                    cols: 2
                    #spacing: 100, 100
                    #padding: 50, 50, 50, 50
                    size_hint:.9,.69
                    id:gre
                    pos_hint:{'center_x':.5,'y':.15}
                    Scroll_A:
                        id: scroll_a
                        scroll_b: scroll_b
                        do_scroll_y: False
                        scroll_y: self.scroll_b.scroll_y
                        pos_hint: {'top': 1}
                        width:gre.width * .15
                        size_hint_x:None
                        SortText:
                            size_hint_y: None
                            #size_hint_x:None
                            
                            id:numb
                            text_size: self.width, None
                            #text: root.rslt if root.result_mod else ''
                            color: 1,1,1,1
                            height: max(self.minimum_height, scroll_a.height)
                            #height: self.texture_size[1]
                            #text: 'X' * 10000
                            disabled:True
                            halign:'center'
                            text: '\n'.join([str(n+1) for n in range(len(strin.text.split('\n')))]) if strin.focus else '\n'.join([str(n+1) for n in range(len(strin.text.split('\n')))])
                    Scroll_B:
                        id: scroll_b
                        width:gre.width*.85
                        do_scroll_y: True
                        pos_hint: {'top': 1}
                        size_hint_x:None
                        SortText:
                            size_hint_y: None
                            id:strin
                            text: root.rslt if root.result_mod else ''
                            multiline: True
                            hint_text: 'Result appears here as output'
                            input_type:'text'
                            keyboard_suggestion:True
                            use_bubble:True
                            allow_copy:True
                            

                            height: max(self.minimum_height, scroll_b.height)
                            
                            text: root.rslt if root.result_mod else ''
                cust_btn:
                    id: Shrink
                    source:'images/shrink.png'
                    pos_hint: {'center_x':self.cust_pos, 'y': .07}
                    size_hint:.91,.06
                    allow_stretch:True
                    keep_ratio:False
                    
                    on_release:
                        Clock.schedule_once(root.seat,0) #if strin.text else strin.focus==True
                        #Clock.schedule_once(root.mode, 2) if emails.text else emails.focus==True
                        #Clock.schedule_once(root.other_tools,2.1)  if '@' in emails.text else print()

                        #Clock.schedule_once(root.generate_emails,2) if emails.text else emails.focus==True
                        #root.other_tools() if '@' in emails.text else root.error_() 

                        Clock.schedule_once(root.shrink, 2)
                        Clock.schedule_once(root.other_tools, 2.1)  if strin.text else print('no')
                        #() #root.shrink()
                        #root.other_tools()  if strin.text else print('no')


        cust_btn:
            source:'images/homebtn.png' if root.result_mod else 'images/scan_back.png' #bottom_back.png'
            pos_hint: {'center_x':self.cust_pos/2.63, 'y': 0}
            size_hint:.28,.06
            allow_stretch:True
            keep_ratio:False
            on_release:
                #root.manager.current='home'
                #print("Can't go back") if root.result_mod else root.dismiss()
                root.home()
        cust_btn:
            source:'images/attach_btn.png' #bottom_back.png'
            pos_hint: {'center_x':self.cust_pos/.759, 'y': 0}
            size_hint:.6,.06
            allow_stretch:True
            keep_ratio:False
            on_release:
                root.show_load()


        BoxLayout:
            id:header
            size_hint:1,.22
            pos_hint:{'left':1,'y':.7}
            FloatLayout:
                Image:
                    source:'images/sort_shrink_footer.png'
                    pos_hint: {'left': 1, 'y': .7}
                    keep_ratio:False
                    allow_stretch:True
                    #size_hint: 1, .3
                Image:
                    source:'images/easyhacks_icon.png'
                    size_hint:.4,.2
                    pos_hint:{'center_x':.2,'y':1.1}

                
                opt_btn:
                    id:sort_page
                    cust_x:.3625
                    source:'images/sort_page.png'
                    pos_hint: {'center_x': self.cust_x, 'y': .75}
                    size_hint: .3*2, .1*2
                    on_press:
                        carousel.load_previous()
                        Animation(cust_x=.15, d=.5).start(sort_bar)
                opt_btn:
                    id:shrink_page
                    source:'images/shrink_page.png'
                    cust_x:.7875
                    pos_hint: {'center_x': self.cust_x, 'y': .75}
                    size_hint: .3*2, .1*2
                    on_press:
                        carousel.load_next(mode= 'next')
                        Animation(cust_x=.575, d= .5).start(sort_bar)
                        print('pressed')
                opt_btn:
                    id:sor_cam
                    source:'images/sort_cam.png'
                    cust_x:.075
                    pos_hint: {'center_x': self.cust_x, 'y': .8}
                    size_hint: .15, .15
                    #allow_stretch:True
                    #keep_ratio:False
                    on_press:
                        root.camera()
                Image:
                    id:sort_bar
                    cust_x:.15
                    source:'images/sort_bar.png'
                    allow_stretch:True
                    keep_ratio:False
                    pos_hint: {'x': self.cust_x, 'y': .7}
                    size_hint: .425, .03
        RectangleFlatButton:
            text:'Tip'
            size_hint:.15, .05
            pos_hint:{'right': 1, 'top': 1}
            on_release:
                root.tip_info()

<LoadDialog>:
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: "vertical"
        FileChooserIconView:
            id: filechooser
            path:root.dir
        BoxLayout:
            size_hint_y: None
            height: '40dp'
            Button:
                text: "Cancel"
                on_release: root.cancel()

            Button:
                text: "Open"
                on_release: root.load(filechooser.path, filechooser.selection)


<Tutorial1>:
    Image:
        source:'images/grey_shade.jpg'
        allow_stretch:True
        keep_ratio:False
        pos_hint:{'bottom':1}
        size_hint:1,.1
    
    Image:
        source:'images/grey_shade.jpg'
        allow_stretch:True
        keep_ratio:False
        pos_hint:{'top':1}
        size_hint:.5,.05
    pointer:
        id:downpin
        source:'images/pointer.png'
        pos_hint:{'center_x':self.cust_pos*root.pos_x,'y':root.pos_y}
        canvas.before:
            PushMatrix
            Rotate:
                angle: -90
                origin:self.center
        canvas.after:
            PopMatrix 
    pointer:
        id:toppin
        source:'images/pointer.png'
        pos_hint:{'center_x':root.mo_x,'y':self.cust_pos+root.mo_y}
        canvas.before:
            PushMatrix
            Rotate:
                angle: 180
                origin:self.center
        canvas.after:
            PopMatrix 
    Label:
        text:'Tutorial Mode'
        pos_hint: {'left':.95, 'top': 1}
        size_hint:.3,.05
        color:0,0,0,1
    TransBtn:
        id:next
        text:'Next'
        size_hint:.3,.05
        pos_hint: {'right':.95, 'y': .02}
        on_release:
            print(root.task)
            root.next_task()
    TransBtn:
        id:active
        text:'End'
        size_hint:.3,.05
        pos_hint: {'x':.05, 'y': .02}
        on_release:
            root.active()


<ActivityNote>:
    FloatLayout:
        
        Label:
            text:'Loading... Please wait....'
            pos_hint:{'center_x':.5,'center_y':.3}
            halign:'center'
            size_hint:.5,.1
        Label:
            text:'Getting things ready... {}%'.format(int(pb.value))
            pos_hint:{'center_x':.5,'center_y':.2}
            halign:'center'
            size_hint:.5,.1
        ProgressBar:
            id:pb
            value:(root.time * 6.6) % 100
            pos_hint:{'center_x':.5,'center_y':.1}
            halign:'center'
            size_hint:1,.1
<Help>:
    Image:
        source:'images/grey_shade.jpg'
        allow_stretch:True
        keep_ratio:False
        pos_hint:{'bottom':1}
        size_hint:1,.1
    
    Image:
        source:'images/grey_shade.jpg'
        allow_stretch:True
        keep_ratio:False
        pos_hint:{'top':1}
        size_hint:.5,.05
    pointer:
        id:downpin
        source:'images/pointer.png'
        pos_hint:{'center_x':self.cust_pos*root.hos_x,'y':root.hos_y}
        canvas.before:
            PushMatrix
            Rotate:
                angle: -90
                origin:self.center
        canvas.after:
            PopMatrix 
    pointer:
        id:toppin
        source:'images/pointer.png'
        pos_hint:{'center_x':root.ho_x,'y':self.cust_pos+root.ho_y}
        canvas.before:
            PushMatrix
            Rotate:
                angle: 180
                origin:self.center
        canvas.after:
            PopMatrix 
    Label:
        text:'Tutorial Mode'
        pos_hint: {'left':.95, 'top': 1}
        size_hint:.3,.05
        color:0,0,0,1
    TransBtn:
        id:next
        text:'Next'
        size_hint:.3,.05
        pos_hint: {'right':.95, 'y': .02}
        on_release:
            print(root.task)
            root.next_task()
    TransBtn:
        id:active
        text:'End'
        size_hint:.3,.05
        pos_hint: {'x':.05, 'y': .02}
        on_release:
            root.active()


<Tutorial3>:
    Image:
        source:'images/grey_shade.jpg'
        allow_stretch:True
        keep_ratio:False
        pos_hint:{'y':.15}
        size_hint:1,.1
    Image:
        source:'images/grey_shade.jpg'
        allow_stretch:True
        keep_ratio:False
        pos_hint:{'top':1}
        size_hint:.5,.05
    pointer:
        id:toppin
        source:'images/pointer.png'
        pos_hint:{'center_x':root.pos_x,'y':self.cust_pos+root.pos_y}
        canvas.before:
            PushMatrix
            Rotate:
                angle: 180
                origin:self.center
        canvas.after:
            PopMatrix 
    
    pointer:
        id:downpin
        opacity:root.bottom
        source:'images/pointer.png'
        pos_hint:{'center_x':root.mov_x,'y':self.cust_pos+root.mov_y}
        
    Label:
        text:'Tutorial Mode'
        pos_hint: {'left':1, 'top': 1}
        size_hint:.3,.05
        color:0,0,0,1
    TransBtn:
        id:next
        text:'Next'
        size_hint:.3,.05
        pos_hint: {'right':.95, 'y': .17}
        on_release:
            root.next_task()
    TransBtn:
        id:active
        text:'End'
        size_hint:.3,.05
        pos_hint: {'x':.05, 'y': .17}
        on_release:
            root.active()

<Tutorial4>:
    Image:
        source:'images/grey_shade.jpg'
        allow_stretch:True
        keep_ratio:False
        pos_hint:{'y':.07}
        size_hint:1,.08
    Image:
        source:'images/grey_shade.jpg'
        allow_stretch:True
        keep_ratio:False
        pos_hint:{'top':1}
        size_hint:.5,.05
    pointer:
        id:toppin
        source:'images/pointer.png'
        pos_hint:{'center_x':self.cust_pos+root.pos_x,'y':.5+root.pos_y}
        canvas.before:
            PushMatrix
            Rotate:
                angle: -90
                origin:self.center
        canvas.after:
            PopMatrix 
    
    pointer:
        id:downpin
        opacity:root.bottom
        source:'images/pointer.png'
        pos_hint:{'center_x':root.mov_x,'y':self.cust_pos+root.mov_y}
        
    Label:
        text:'Tutorial Mode'
        pos_hint: {'x':.1, 'top': 1}
        size_hint:.3,.05
        color:0,0,0,1
    TransBtn:
        id:next
        text:'Next'
        size_hint:.3,.05
        pos_hint: {'right':.95, 'y': .08}
        on_release:
            root.next_task()
    TransBtn:
        id:active
        text:'End'
        size_hint:.3,.05
        pos_hint: {'x':.05, 'y': .08}
        on_release:
            root.active()

<Tutorial5>:
    Image:
        source:'images/grey_shade.jpg'
        allow_stretch:True
        keep_ratio:False
        pos_hint:{'y':.15}
        size_hint:1,.1
    Image:
        source:'images/grey_shade.jpg'
        allow_stretch:True
        keep_ratio:False
        pos_hint:{'top':1}
        size_hint:.5,.05
    pointer:
        id:toppin
        source:'images/pointer.png'
        pos_hint:{'center_x':root.pos_x,'y':self.cust_pos+root.pos_y}
        canvas.before:
            PushMatrix
            Rotate:
                angle: 180
                origin:self.center
        canvas.after:
            PopMatrix 
    
    pointer:
        id:downpin
        opacity:root.bottom
        source:'images/pointer.png'
        pos_hint:{'center_x':root.mov_x,'y':self.cust_pos+root.mov_y}
        
    Label:
        text:'Tutorial Mode'
        pos_hint: {'left':1, 'top': 1}
        size_hint:.3,.05
        color:0,0,0,1
    TransBtn:
        id:next
        text:'Next'
        size_hint:.3,.05
        pos_hint: {'right':.95, 'y': .17}
        on_release:
            root.next_task()
    TransBtn:
        id:active
        text:'End'
        size_hint:.3,.05
        pos_hint: {'x':.05, 'y': .17}
        on_release:
            root.active()


<Tutorial2>:
    Image:
        source:'images/grey_shade.jpg'
        allow_stretch:True
        keep_ratio:False
        pos_hint:{'y':.15}
        size_hint:1,.1
    Image:
        source:'images/grey_shade.jpg'
        allow_stretch:True
        keep_ratio:False
        pos_hint:{'top':1}
        size_hint:.5,.05
    pointer:
        id:toppin
        source:'images/pointer.png'
        pos_hint:{'center_x':root.pos_x,'y':self.cust_pos+root.pos_y}
        canvas.before:
            PushMatrix
            Rotate:
                angle: 180
                origin:self.center
        canvas.after:
            PopMatrix 
    
    pointer:
        id:downpin
        opacity:root.bottom
        source:'images/pointer.png'
        pos_hint:{'center_x':root.mov_x,'y':self.cust_pos+root.mov_y}
        
    Label:
        text:'Tutorial Mode'
        pos_hint: {'left':1, 'top': 1}
        size_hint:.3,.05
        color:0,0,0,1
    TransBtn:
        id:next
        text:'Next'
        size_hint:.3,.05
        pos_hint: {'right':.95, 'y': .17}
        on_release:
            root.next_task()
    TransBtn:
        id:active
        text:'End'
        size_hint:.3,.05
        pos_hint: {'x':.05, 'y': .17}
        on_release:
            root.active()
    
    

<CamBox>:
    FloatLayout:
        orientation:'vertical'
        Camera:
            id:cam
            resolution:(1280,960) 
            size_hint:1.4,.5
            pos_hint:{'center_x':.5,'top':1}
            play:True
            keep_ratio:False
            allow_stretch:True
            canvas.before:
                PushMatrix
                Rotate:
                    angle: -90
                    origin:self.center
            canvas.after:
                PopMatrix 
        opt_btn:
            source:'images/shutter_click.png' if self.state == 'down' else 'images/shutter.png'
            size_hint:.3,.3
            pos_hint:{'center_x':.5,'center_y':.2}
            #size_hint_y:15
            #height:'48dp'
            #text:'Capture'
            on_press:
                #cam.play=False 
                root.aftermat()
        
                
        BoxLayout:
            id:imgs
            pos_hint:{'center_x':.5,'center_y':.1}
            size_hint:1,.1
        opt_btn:
            source:'images/done.png'
            size_hint:.3,.05
            pos_hint:{'center_x':.8,'center_y':.05}
            #size_hint_y:None
            
            on_release:
                root.flash_on()
                root.pop_close()
                root.flash_release()
                root.dismiss()
            
        opt_btn:
            source:'images/cancel.png'
            size_hint:.3,.05
            pos_hint:{'center_x':.2,'center_y':.05}
            #size_hint_y:None
            on_release:
                
                root.add_image()
                #root.pop_close()
                roo.flash_on()
                root.flash_release()
                root.dismiss()
            


<ProfileDetails>:
    FloatLayout:
        Image:
            source:'images/contact_board.png'
            size_hint:1,.3
            pos_hint:{'top':1}
            allow_stretch:True
            keep_ratio:False
        Image:
            source:'images/contact_head.png'
            size_hint:.3,.3
            pos_hint:{'x':.1,'y':.7}
        Label:
            text:root.name
            size_hint:.3,.3
            pos_hint:{'x':.6,'y':.7}
        BoxLayout:
            size_hint:1,.7
            pos_hint:{'bottom':1}
            orientation:'vertical'
            BoxLayout:
                size_hint_y:90
                BoxLayout
                    orientation:'vertical'
                    size_hint_x:40
                    Label:
                        text:'Email Address:'
                        halign:'left'
                    Label:
                        text:'Phone:'
                        halign:'left'
                    Label:
                        text:'Web Address:'
                        halign:'left'
                    Label:
                        text:'Physical Address:'
                        halign:'left'
                BoxLayout:
                    size_hint_x:60
                    orientation:'vertical'
                    Button:
                        text:root.email
                        background_normal:'images/effect_empty.png'
                        background_down:'images/contact_board.png'
                        on_release:
                            root.msg(root.email)
                    Button:
                        text:root.phone
                        background_normal:'images/effect_empty.png'
                        background_down:'images/contact_board.png'
                        on_release:
                            root.call(root.phone)
                    Button:
                        text:root.link
                        background_normal:'images/effect_empty.png'
                        background_down:'images/contact_board.png'
                        on_release:
                            root.open_link(root.link)
                    Button:
                        text:root.address
                        background_normal:'images/effect_empty.png'
                        background_down:'images/contact_board.png'
                        on_release:
                            root.map_direction(root.address)
                        
                        
            Button:
                text:'Done'
                size_hint_y:10
                on_press:root.dismiss()
            
<ProfileAnalyse>:
    FloatLayout:
        Image:
            source:'images/contact_board.png'
            size_hint:1,.3
            pos_hint:{'top':1}
            allow_stretch:True
            keep_ratio:False
        Image:
            source:'images/contact_head.png'
            size_hint:.3,.3
            pos_hint:{'x':.1,'y':.7}
        Label:
            text:root.name
            size_hint:.3,.3
            pos_hint:{'x':.6,'y':.7}
        BoxLayout:
            size_hint:1,.4
            pos_hint:{'top':.7}
            orientation:'vertical'
            BoxLayout:
                size_hint_y:90
                BoxLayout
                    orientation:'vertical'
                    size_hint_x:40
                    Label:
                        text:'Name:'
                        halign:'left'
                    Label:
                        text:'Email Address:'
                        halign:'left'
                    Label:
                        text:'Phone:'
                        halign:'left'
                    Label:
                        text:'Web Address:'
                        halign:'left'
                    Label:
                        text:'Physical Address:'
                        halign:'left'
                BoxLayout:
                    size_hint_x:60
                    orientation:'vertical'
                    TextInput:
                        id:name
                        text:root.name
                    TextInput:
                        id:email
                        text:root.email
                        
                        
                    TextInput:
                        id:phone
                        text:root.phone
                        
                    TextInput:
                        id:link
                        text:root.link
                        
                        
                    TextInput:
                        id:address
                        text:root.address
                    
                        
                        
                        
            BoxLayout:
                size_hint_y:10
                Button:
                    text:'Close'
                    
                    on_press:
                        #root.save_profile()
                        root.dismiss()
                Button:
                    text:'Save'
                    #size_hint_y:10
                    on_press:
                        root.save_profile()
                        root.dismiss()



<ResultMode>:
    id:extract_mode
    Image:
        source:'images/mode_frame.png'
        size_hint:.9,.2
        pos_hint:{'x':-.8,'center_y':.3}
    sld_btn:
        source:'images/Xmode_click.png' if self.state =='down' else 'images/Xmode.png'
        size_hint:.06,.12
        pos_hint:{'x':.03,'center_y':.3}
        on_press:
            Animation(x=extract_mode.width/1.3, d=.5).start(extract_mode)
    sld_btn:
        source:'images/share_click.png' if self.state =='down' else 'images/share.png'
        size_hint:.17,.15
        pos_hint:{'x':-.17,'center_y':.3}
        on_press:
            Animation(x=0, d=.5).start(extract_mode)
            root.share() #new_email()  #whatsapp() # open_link() #
    sld_btn:
        source:'images/copy_click.png' if self.state =='down' else 'images/copy.png'
        size_hint:.2,.15
        pos_hint:{'x':-.385,'center_y':.3}
        on_press:
            Animation(x=0, d=.5).start(extract_mode)
            root.copy()   #screenshot() #copy()
            
    sld_btn:
        source:'images/paste_click.png' if self.state =='down' else 'images/paste.png'
        size_hint:.2,.15
        pos_hint:{'x':-.588,'center_y':.3}
        on_press:
            Animation(x=0, d=.5).start(extract_mode)
            root.save_result()
    sld_btn:
        source:'images/delete_click.png' if self.state =='down' else 'images/delete.png'
        size_hint:.2,.15
        pos_hint:{'x':-.79,'center_y':.3}
        on_press:
            Animation(x=0, d=.5).start(extract_mode)
            root.show_errors() #open_link() #send_text() #delete_()



<AnalyseProfile>:
    size_hint: .5, .5
    pos_hint: {'center_x': .5, 'center_y': .5}
    do_default_tab: False
    TabbedPanelItem:
        text: 'Emails'
        TextInput
            text:root.emails
    TabbedPanelItem:
        text: 'Links'
        TextInput:
            text:root.links
    TabbedPanelItem:
        text: 'Phone'
        TextInput:
            text:root.phone
    TabbedPanelItem:
        text: 'Physical Address'
        TextInput:
            text:root.others
    
    TabbedPanelItem:
        text: 'Name'
        TextInput:
            text:root.name
        